name: SydhavnsCompagniets Venner
favicon: null
layout_spectrum: 0.8856321044731885
typography_spectrum: 0.8616376011632383
title: SydhavnsCompagniets Venner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4920564314816147
  lightness: 0.9016311997547746
  saturation: 0.46272619161754847
  rhythmicContrast: 0.139753851108253
purpose: []
